package br.edu.utfpr.cm.es2.cvlates.view;

import javax.swing.JOptionPane;

import br.edu.utfpr.cm.es2.cvlates.controller.UsuarioController;
import br.edu.utfpr.cm.es2.cvlates.entity.Usuario;

public class PainelCadastraUsuario extends javax.swing.JFrame {

	/**
	 * 
	 */
	private UsuarioController uControl;
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form PainelCadastraUsuario
	 */
	public PainelCadastraUsuario() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		this.uControl = new UsuarioController();
		adicionarButton = new javax.swing.JButton();
		casdastroUsuarioLabel = new javax.swing.JLabel();
		nomeLabel = new javax.swing.JLabel();
		nomeTextField = new javax.swing.JTextField();
		emailLabel = new javax.swing.JLabel();
		emailTextField = new javax.swing.JTextField();
		cpflabel = new javax.swing.JLabel();
		cpfTextField = new javax.swing.JTextField();
		senhaPassWordField = new javax.swing.JPasswordField();
		confirmaSenhaField = new javax.swing.JPasswordField();
		senhaLabel = new javax.swing.JLabel();
		confirmaSenhaLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		adicionarButton.setText("Adicionar");
		adicionarButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		casdastroUsuarioLabel.setText("Cadastrar Usu·rio");

		nomeLabel.setText("Nome:");

		emailLabel.setText("email:");

		cpflabel.setText("cpf:");

		senhaLabel.setText("Senha:");

		confirmaSenhaLabel.setText("Confirmar senha:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(213, 213, 213)
								.addComponent(casdastroUsuarioLabel).addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGap(74, 74, 74)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(cpflabel).addComponent(emailLabel).addComponent(senhaLabel)
										.addComponent(confirmaSenhaLabel).addComponent(nomeLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
														164, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(0, 0, Short.MAX_VALUE))
										.addComponent(senhaPassWordField).addComponent(emailTextField)
										.addComponent(cpfTextField).addComponent(confirmaSenhaField))))
						.addGap(162, 162, 162))
				.addGroup(layout.createSequentialGroup().addGap(206, 206, 206).addComponent(adicionarButton)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(casdastroUsuarioLabel).addGap(50, 50, 50)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nomeLabel).addComponent(nomeTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(emailLabel).addComponent(emailTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cpflabel).addComponent(cpfTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(senhaPassWordField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(senhaLabel))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(confirmaSenhaField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(confirmaSenhaLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
						.addComponent(adicionarButton).addGap(19, 19, 19)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Usuario u = new Usuario();
		boolean confirma = true;
		if (nomeTextField.getText().matches("^[A-Za-z·‡‚„ÈËÍÌÔÛÙıˆ˙ÁÒ¡¿¬√…»Õœ”‘’÷⁄«— ]+$")) {
			confirma = true;
			u.setNome(nomeTextField.getText());
		} else {
			confirma = false;
			JOptionPane.showMessageDialog(null, "Erro na validaÁ„o de nome", "Erro", JOptionPane.ERROR_MESSAGE);
		}
		if (emailTextField.getText().matches("[A-Za-z0-9\\._-]+@[A-Za-z]+\\.[A-Za-z]+")) {
			u.setEmail(this.emailTextField.getText());
			confirma = true;
		} else {
			confirma = false;
			JOptionPane.showMessageDialog(null, "Formato de email contÈm erros", "Erro", JOptionPane.ERROR_MESSAGE);
		}
		if (cpfTextField.getText().matches(
				"([0-9]{2}[\\.]?[0-9]{3}[\\.]?[0-9]{3}[\\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\\.]?[0-9]{3}[\\.]?[0-9]{3}[-]?[0-9]{2})")) {
			confirma = true;
			u.setCpf(cpfTextField.getText());
		} else {
			confirma = false;
		}
		if (senhaPassWordField.getText().equals(confirmaSenhaField.getText())) {
			if (senhaPassWordField.getText().isEmpty()) {
				confirma = false;
				JOptionPane.showMessageDialog(null, "Erro: campo de senha est· vazio", "Erro",
						JOptionPane.ERROR_MESSAGE);
			} else {
				confirma = true;
				u.setSenha(this.senhaPassWordField.getText());
			}
		}
		if (confirma == true) {
			boolean crudRealizado = true;
			u.setAtivo(true);
			try {
				uControl.persist(u);

			} catch (Exception e) {
				crudRealizado = false;
				JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
			} finally {
				if(crudRealizado == false) {
					JOptionPane.showMessageDialog(null, "N„o foi PossÌvel realizaÁ„o de CRUD","Erro",JOptionPane.ERROR_MESSAGE);
				}
				else {
					JOptionPane.showMessageDialog(null, "CRUD realizado com sucesso","ConfirmaÁ„o",JOptionPane.INFORMATION_MESSAGE);
				}
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PainelCadastraUsuario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PainelCadastraUsuario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PainelCadastraUsuario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PainelCadastraUsuario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PainelCadastraUsuario().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton adicionarButton;
	private javax.swing.JLabel casdastroUsuarioLabel;
	private javax.swing.JLabel nomeLabel;
	private javax.swing.JLabel emailLabel;
	private javax.swing.JLabel cpflabel;
	private javax.swing.JLabel senhaLabel;
	private javax.swing.JLabel confirmaSenhaLabel;
	private javax.swing.JPasswordField senhaPassWordField;
	private javax.swing.JPasswordField confirmaSenhaField;
	private javax.swing.JTextField nomeTextField;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JTextField cpfTextField;
	// End of variables declaration
}
